name = "text-effects-editor"
compatibility_date = "2026-07-10"
pages_build_output_dir = "dist"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "font-effects-gallery"
database_id = "78da3b07-5090-4fd8-b0a3-8a2d5397c754"
